### ISSUE TITLE
1.21.5 jar version is incompatible with 1.21.8 due mapping difference

### ISSUE THREAD

**Issue by FoxieFlakey** [IsaiahMC/multiworld#131]
From 1.21.5's fabric.mod.json claims it works on 1.21.5 to 1.21.8 (both inclusive link: [fabric.mod.json](https://github.com/IsaiahMC/multiworld/blob/6750cb8913341b37184575063cedc17d3370b716/Multiworld-Fabric-1.21.5/src/main/resources/fabric.mod.json)) but when I ran it, it doesn't work the symptons are this exception and then a crash

```
[11:38:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_1937 net.minecraft.class_1657.method_5770()'
        at knot/me.isaiah.multiworld.portal.WandEventHandler.setPosition(WandEventHandler.java:69) ~[multiworld-1.10-1614f4285e480ce0.jar:?]
        at knot/me.isaiah.multiworld.portal.WandEventHandler.leftClickBlock(WandEventHandler.java:37) ~[multiworld-1.10-1614f4285e480ce0.jar:?]
        at knot/me.isaiah.multiworld.fabric.FabricEvents.lambda$register$0(FabricEvents.java:11) ~[multiworld-1.10-1614f4285e480ce0.jar:?]
        at knot/net.fabricmc.fabric.api.event.player.AttackBlockCallback.lambda$static$0(AttackBlockCallback.java:51) ~[fabric-events-interaction-v0-4.0+946bf4c32c-8503b88da9540db4.jar:?]
        at knot/net.minecraft.class_3225.handler$zma000$fabric-events-interaction-v0$startBlockBreak(class_3225.java:1061) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3225.method_14263(class_3225.java) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3244.method_12066(class_3244.java:1305) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2846.method_12361(class_2846.java:50) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2846.method_65081(class_2846.java:10) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:883) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:179) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:865) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:859) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:827) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713) [server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:291) [server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) [?:?]
```

method_5770 doesn't exist in 1.21.8 however the code at [WandEventHandler.java#L69](https://github.com/IsaiahMC/multiworld/blob/6750cb8913341b37184575063cedc17d3370b716/Multiworld-Common/src/main/java/me/isaiah/multiworld/portal/WandEventHandler.java#L69) is

```java
positions[0] = (ServerWorld) player.getEntityWorld();
```

`getEntityWorld` does exist as [method_5770](https://maven.fabricmc.net/docs/yarn-1.21.5+build.1/net/minecraft/entity/Entity.html#getEntityWorld()) on 1.21.5 yarn mapping but i've check on 1.21.6 in [PlayerEntity](https://maven.fabricmc.net/docs/yarn-1.21.6+build.1/net/minecraft/entity/player/PlayerEntity.html) class and its super classes manually, its removed on 1.21.6 and does not exist on later versions.

# The fix suggestion

But `getWorld` also exist on 1.21.5 and later so should use that instead of `getEntityWorld` both returns `World` and last time I do modding (currently unable to view the code for sure) on older versions both are interchangeable and its located at Entity class (one superclass of PlayerEntity). Also replace all the `getEntityWorld` references with `getWorld` and it should work.

Small background: I've done few modding in Minecraft uses Fabric and Yarn but I've not check the code if getWorld and getEntityWorld is equivalent (in that getEntityWorld can be replaced with getWorld instead) because decompiling and deobfuscating two Minecraft versions took ages on my sadness pair of 9th gen Intel celerons AGES so try check it yourself I was manually reading javadocs because took ages to create my local copies which my IDE can find easier. I'd consider myself be intermediate.

I can try create a pull request if its properly confirmed and is correct fix because wanting to ask if that even works or not.

Notes: Links are provided as permalink to the HEAD at the point of writing of this issue

**Comment by jahndae17** [comment]
@FoxieFlakey 

Did you have a patched jar that might save me the effort of compiling?
